Knusperleicht\EpsBankTransfer\Internal\Generated\BankList\EpsSOBankListProtocol\EpsSOBankListProtocolAType:
    properties:
        bank:
            expose: true
            access_type: public_method
            serialized_name: bank
            xml_element:
                namespace: 'http://www.eps.or.at/epsSO/epsSOBankListProtocol/201008'
            accessor:
                getter: getBank
                setter: setBank
            xml_list:
                inline: true
                entry_name: bank
                namespace: 'http://www.eps.or.at/epsSO/epsSOBankListProtocol/201008'
            type: array<Knusperleicht\EpsBankTransfer\Internal\Generated\BankList\BankDataType>
        errorDetails:
            expose: true
            access_type: public_method
            serialized_name: errorDetails
            xml_element:
                namespace: 'http://www.eps.or.at/epsSO/epsSOBankListProtocol/201008'
            accessor:
                getter: getErrorDetails
                setter: setErrorDetails
            type: Knusperleicht\EpsBankTransfer\Internal\Generated\BankList\ErrorDataType
