Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V26\BankResponseDetails:
    xml_root_name: BankResponseDetails
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
