Psa\EpsBankTransfer\Internal\Generated\Protocol\V26\ConfirmationStatusRequest:
    xml_root_name: ConfirmationStatusRequest
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
