Externet\EpsBankTransfer\Generated\Protocol\V26\EpsProtocolDetails\EpsProtocolDetailsAType:
    properties:
        sessionLanguage:
            expose: true
            access_type: public_method
            serialized_name: SessionLanguage
            accessor:
                getter: getSessionLanguage
                setter: setSessionLanguage
            xml_attribute: true
            type: string
        transferInitiatorDetails:
            expose: true
            access_type: public_method
            serialized_name: TransferInitiatorDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getTransferInitiatorDetails
                setter: setTransferInitiatorDetails
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\TransferInitiatorDetails
        bankResponseDetails:
            expose: true
            access_type: public_method
            serialized_name: BankResponseDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getBankResponseDetails
                setter: setBankResponseDetails
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\BankResponseDetails
        vitalityCheckDetails:
            expose: true
            access_type: public_method
            serialized_name: VitalityCheckDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getVitalityCheckDetails
                setter: setVitalityCheckDetails
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\VitalityCheckDetails
        bankConfirmationDetails:
            expose: true
            access_type: public_method
            serialized_name: BankConfirmationDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getBankConfirmationDetails
                setter: setBankConfirmationDetails
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\BankConfirmationDetails
        shopResponseDetails:
            expose: true
            access_type: public_method
            serialized_name: ShopResponseDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getShopResponseDetails
                setter: setShopResponseDetails
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\ShopResponseDetails
        transactionDetailsRequest:
            expose: true
            access_type: public_method
            serialized_name: TransactionDetailsRequest
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getTransactionDetailsRequest
                setter: setTransactionDetailsRequest
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\TransactionDetailsRequest
        transactionDetailsResponse:
            expose: true
            access_type: public_method
            serialized_name: TransactionDetailsResponse
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getTransactionDetailsResponse
                setter: setTransactionDetailsResponse
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\TransactionDetailsResponse
        confirmationStatusRequest:
            expose: true
            access_type: public_method
            serialized_name: ConfirmationStatusRequest
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getConfirmationStatusRequest
                setter: setConfirmationStatusRequest
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\ConfirmationStatusRequest
        confirmationStatusResponse:
            expose: true
            access_type: public_method
            serialized_name: ConfirmationStatusResponse
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getConfirmationStatusResponse
                setter: setConfirmationStatusResponse
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\ConfirmationStatusResponse
        statusMsg:
            expose: true
            access_type: public_method
            serialized_name: StatusMsg
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getStatusMsg
                setter: setStatusMsg
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\StatusMsg
