Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V26\ErrorDetails\ErrorDetailsAType:
    properties:
        errorCode:
            expose: true
            access_type: public_method
            serialized_name: ErrorCode
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getErrorCode
                setter: setErrorCode
            type: string
        errorMsg:
            expose: true
            access_type: public_method
            serialized_name: ErrorMsg
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getErrorMsg
                setter: setErrorMsg
            type: string
