Psa\EpsBankTransfer\Internal\Generated\Protocol\V26\MD5Fingerprint:
    xml_root_name: MD5Fingerprint
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
