Psa\EpsBankTransfer\Generated\Protocol\V26\TransactionDetailsResponse\TransactionDetailsResponseAType:
    properties:
        paymentInitiatorDetails:
            expose: true
            access_type: public_method
            serialized_name: PaymentInitiatorDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2014/10'
            accessor:
                getter: getPaymentInitiatorDetails
                setter: setPaymentInitiatorDetails
            type: Psa\EpsBankTransfer\Generated\Payment\V26\PaymentInitiatorDetails
        transferMsgDetails:
            expose: true
            access_type: public_method
            serialized_name: TransferMsgDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getTransferMsgDetails
                setter: setTransferMsgDetails
            type: Psa\EpsBankTransfer\Generated\Protocol\V26\TransferMsgDetails
        webshopDetails:
            expose: true
            access_type: public_method
            serialized_name: WebshopDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getWebshopDetails
                setter: setWebshopDetails
            type: array<Psa\EpsBankTransfer\Generated\Protocol\V26\WebshopArticle>
            xml_list:
                inline: false
                entry_name: WebshopArticle
                skip_when_empty: true
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
        signature:
            expose: true
            access_type: public_method
            serialized_name: Signature
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getSignature
                setter: setSignature
            type: Psa\EpsBankTransfer\Generated\XmlDsig\Signature
        errorDetails:
            expose: true
            access_type: public_method
            serialized_name: ErrorDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getErrorDetails
                setter: setErrorDetails
            type: Psa\EpsBankTransfer\Generated\Protocol\V26\ErrorDetails
