Psa\EpsBankTransfer\Internal\Generated\Protocol\V26\TransactionDetailsResponse:
    xml_root_name: TransactionDetailsResponse
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
