Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V26\TransferMsgDetails\TransferMsgDetailsAType:
    properties:
        confirmationUrl:
            expose: true
            access_type: public_method
            serialized_name: ConfirmationUrl
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getConfirmationUrl
                setter: setConfirmationUrl
            type: string
        transactionOkUrl:
            expose: true
            access_type: public_method
            serialized_name: TransactionOkUrl
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getTransactionOkUrl
                setter: setTransactionOkUrl
            type: Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V26\TransactionOkUrl
        transactionNokUrl:
            expose: true
            access_type: public_method
            serialized_name: TransactionNokUrl
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getTransactionNokUrl
                setter: setTransactionNokUrl
            type: Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V26\TransactionNokUrl
