Externet\EpsBankTransfer\Generated\Protocol\V26\TransferInitiatorDetails\TransferInitiatorDetailsAType:
    properties:
        paymentInitiatorDetails:
            expose: true
            access_type: public_method
            serialized_name: PaymentInitiatorDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2014/10'
            accessor:
                getter: getPaymentInitiatorDetails
                setter: setPaymentInitiatorDetails
            type: Externet\EpsBankTransfer\Generated\Payment\V26\PaymentInitiatorDetails
        transferMsgDetails:
            expose: true
            access_type: public_method
            serialized_name: TransferMsgDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getTransferMsgDetails
                setter: setTransferMsgDetails
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\TransferMsgDetails
        webshopDetails:
            expose: true
            access_type: public_method
            serialized_name: WebshopDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getWebshopDetails
                setter: setWebshopDetails
            type: array<Externet\EpsBankTransfer\Generated\Protocol\V26\WebshopArticle>
            xml_list:
                inline: false
                entry_name: WebshopArticle
                skip_when_empty: true
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
        transactionId:
            expose: true
            access_type: public_method
            serialized_name: TransactionId
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getTransactionId
                setter: setTransactionId
            type: string
        qRCodeUrl:
            expose: true
            access_type: public_method
            serialized_name: QRCodeUrl
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getQRCodeUrl
                setter: setQRCodeUrl
            type: string
        authenticationDetails:
            expose: true
            access_type: public_method
            serialized_name: AuthenticationDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2014/10'
            accessor:
                getter: getAuthenticationDetails
                setter: setAuthenticationDetails
            type: Externet\EpsBankTransfer\Generated\Protocol\V26\AuthenticationDetails
