Psa\EpsBankTransfer\Internal\Generated\Payment\V27\PayConApprovingUnitDetails:
    xml_root_name: PayConApprovingUnitDetails
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
