Externet\EpsBankTransfer\Generated\Payment\V27\PaymentConfirmationDetails\PaymentConfirmationDetailsAType:
    properties:
        remittanceIdentifier:
            expose: true
            access_type: public_method
            serialized_name: RemittanceIdentifier
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/epi/2013/02'
            accessor:
                getter: getRemittanceIdentifier
                setter: setRemittanceIdentifier
            type: string
        unstructuredRemittanceIdentifier:
            expose: true
            access_type: public_method
            serialized_name: UnstructuredRemittanceIdentifier
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/epi/2013/02'
            accessor:
                getter: getUnstructuredRemittanceIdentifier
                setter: setUnstructuredRemittanceIdentifier
            type: string
        paymentInitiatorDetails:
            expose: true
            access_type: public_method
            serialized_name: PaymentInitiatorDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
            accessor:
                getter: getPaymentInitiatorDetails
                setter: setPaymentInitiatorDetails
            type: Externet\EpsBankTransfer\Generated\Payment\V27\PaymentInitiatorDetails
        payConApprovingUnitDetails:
            expose: true
            access_type: public_method
            serialized_name: PayConApprovingUnitDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
            accessor:
                getter: getPayConApprovingUnitDetails
                setter: setPayConApprovingUnitDetails
            type: Externet\EpsBankTransfer\Generated\Payment\V27\PayConApprovingUnitDetails
        payConApprovalTime:
            expose: true
            access_type: public_method
            serialized_name: PayConApprovalTime
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
            accessor:
                getter: getPayConApprovalTime
                setter: setPayConApprovalTime
            type: DateTime
        paymentReferenceIdentifier:
            expose: true
            access_type: public_method
            serialized_name: PaymentReferenceIdentifier
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
            accessor:
                getter: getPaymentReferenceIdentifier
                setter: setPaymentReferenceIdentifier
            type: string
        statusCode:
            expose: true
            access_type: public_method
            serialized_name: StatusCode
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
            accessor:
                getter: getStatusCode
                setter: setStatusCode
            type: string
        statusReason:
            expose: true
            access_type: public_method
            serialized_name: StatusReason
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
            accessor:
                getter: getStatusReason
                setter: setStatusReason
            type: Externet\EpsBankTransfer\Generated\Payment\V27\StatusReason
        signature:
            expose: true
            access_type: public_method
            serialized_name: Signature
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getSignature
                setter: setSignature
            type: Externet\EpsBankTransfer\Generated\XmlDsig\Signature
