Psa\EpsBankTransfer\Generated\Payment\V27\PaymentInitiatorDetails\PaymentInitiatorDetailsAType:
    properties:
        epiDetails:
            expose: true
            access_type: public_method
            serialized_name: EpiDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/epi/2013/02'
            accessor:
                getter: getEpiDetails
                setter: setEpiDetails
            type: Psa\EpsBankTransfer\Generated\Epi\EpiDetails
        austrianRulesDetails:
            expose: true
            access_type: public_method
            serialized_name: AustrianRulesDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/austrianrules/2014/10'
            accessor:
                getter: getAustrianRulesDetails
                setter: setAustrianRulesDetails
            type: Psa\EpsBankTransfer\Generated\AustrianRules\AustrianRulesDetails
