Psa\EpsBankTransfer\Generated\Payment\V27\ReasonCode:
    xml_root_name: ReasonCode
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
