Psa\EpsBankTransfer\Generated\Payment\V27\ShopConfirmationDetails\ShopConfirmationDetailsAType:
    properties:
        statusCode:
            expose: true
            access_type: public_method
            serialized_name: StatusCode
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
            accessor:
                getter: getStatusCode
                setter: setStatusCode
            type: string
        paymentReferenceIdentifier:
            expose: true
            access_type: public_method
            serialized_name: PaymentReferenceIdentifier
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
            accessor:
                getter: getPaymentReferenceIdentifier
                setter: setPaymentReferenceIdentifier
            type: string
