Psa\EpsBankTransfer\Internal\Generated\Payment\V27\StatusCode:
    xml_root_name: StatusCode
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
