<?php
declare(strict_types=1);

namespace Knusperleicht\EpsBankTransfer\Responses;

use Knusperleicht\EpsBankTransfer\Internal\Generated\Payment\V26\ShopConfirmationDetails;
use Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V26\EpsProtocolDetails;

class ShopResponseDetails
{
    /**
     * Build EPS v2.6 schema object from domain ShopResponseDetails.
     *
     * Returns an EpsProtocolDetails payload ready to be serialized and sent back
     * to the Scheme Operator (SO) as confirmation response.
     *
     * Rules (v2.6):
     * - When errorMessage is set, only ErrorMsg (and optional SessionId) is populated.
     * - Otherwise a ShopConfirmationDetails block with StatusCode and PaymentReferenceIdentifier is provided.
     */
    /** @var string Human-readable error message provided by the shop, if any */
    public $errorMessage;

    /** @var string Session identifier generated by the bank */
    public $sessionId;

    /** @var string Status code of the EPS transaction as returned by the bank */
    public $statusCode;

    /** @var string Bank-generated payment reference identifier */
    public $paymentReferenceIdentifier;

    /**
     * Domain to EPS schema mapping (v2.6).
     *
     * @return EpsProtocolDetails Fully populated response ready to return to SO.
     */
    public function toV26(): EpsProtocolDetails
    {
        $epsProtocolDetails = new EpsProtocolDetails();
        $shopResponseDetails = new \Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V26\ShopResponseDetails();

        if (!empty($this->errorMessage)) {
            $shopResponseDetails->setErrorMsg($this->errorMessage);
            if (!empty($this->sessionId)) {
                $shopResponseDetails->setSessionId($this->sessionId);
            }
        } else {
            $shopResponseDetails->setSessionId($this->sessionId);

            $shopConfirmationDetails = new ShopConfirmationDetails();
            $shopConfirmationDetails->setStatusCode($this->statusCode);
            $shopConfirmationDetails->setPaymentReferenceIdentifier($this->paymentReferenceIdentifier);
            $shopResponseDetails->setShopConfirmationDetails($shopConfirmationDetails);
        }

        $epsProtocolDetails->setShopResponseDetails($shopResponseDetails);
        return $epsProtocolDetails;
    }

    /**
     * @param string $statusCode
     */
    public function setStatusCode(string $statusCode): void
    {
        $this->statusCode = $statusCode;
    }

    /**
     * @param string $sessionId
     */
    public function setSessionId(string $sessionId): void
    {
        $this->sessionId = $sessionId;
    }

    /**
     * @param string $paymentReferenceIdentifier
     */
    public function setPaymentReferenceIdentifier(string $paymentReferenceIdentifier): void
    {
        $this->paymentReferenceIdentifier = $paymentReferenceIdentifier;
    }

    /**
     * @param string $errorMessage
     */
    public function setErrorMessage(string $errorMessage): void
    {
        $this->errorMessage = $errorMessage;
    }
}