Psa\EpsBankTransfer\Generated\Payment\V26\ApprovingUnitBankIdentifier:
    xml_root_name: ApprovingUnitBankIdentifier
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/payment/2014/10'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
