Externet\EpsBankTransfer\Generated\Payment\V26\PayConApprovingUnitDetails\PayConApprovingUnitDetailsAType:
    properties:
        approvingUnitBankIdentifier:
            expose: true
            access_type: public_method
            serialized_name: ApprovingUnitBankIdentifier
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2014/10'
            accessor:
                getter: getApprovingUnitBankIdentifier
                setter: setApprovingUnitBankIdentifier
            type: string
        approvingUnitIdentifier:
            expose: true
            access_type: public_method
            serialized_name: ApprovingUnitIdentifier
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2014/10'
            accessor:
                getter: getApprovingUnitIdentifier
                setter: setApprovingUnitIdentifier
            type: string
