Knusperleicht\EpsBankTransfer\Internal\Generated\Payment\V26\PaymentConfirmationDetails:
    xml_root_name: PaymentConfirmationDetails
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/payment/2014/10'
