Knusperleicht\EpsBankTransfer\Internal\Generated\Payment\V26\ShopConfirmationDetails:
    xml_root_name: ShopConfirmationDetails
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/payment/2014/10'
