Psa\EpsBankTransfer\Generated\Refund\Amount\AmountAType:
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: float
        amountCurrencyIdentifier:
            expose: true
            access_type: public_method
            serialized_name: AmountCurrencyIdentifier
            accessor:
                getter: getAmountCurrencyIdentifier
                setter: setAmountCurrencyIdentifier
            xml_attribute: true
            type: string
