Knusperleicht\EpsBankTransfer\Internal\Generated\Refund\AuthenticationDetails\AuthenticationDetailsAType:
    properties:
        userId:
            expose: true
            access_type: public_method
            serialized_name: UserId
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/refund/2018/09'
            accessor:
                getter: getUserId
                setter: setUserId
            type: string
        sHA256Fingerprint:
            expose: true
            access_type: public_method
            serialized_name: SHA256Fingerprint
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/refund/2018/09'
            accessor:
                getter: getSHA256Fingerprint
                setter: setSHA256Fingerprint
            type: string
        signature:
            expose: true
            access_type: public_method
            serialized_name: Signature
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getSignature
                setter: setSignature
            type: Knusperleicht\EpsBankTransfer\Internal\Generated\XmlDsig\Signature
