Psa\EpsBankTransfer\Internal\Generated\Refund\RefundReference:
    xml_root_name: RefundReference
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/refund/2018/09'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
