Knusperleicht\EpsBankTransfer\Internal\Generated\AustrianRules\DigSig:
    xml_root_name: DigSig
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/austrianrules/2014/10'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
