Psa\EpsBankTransfer\Generated\AustrianRules\TradeCategoryDetails\TradeCategoryDetailsAType:
    properties:
        code:
            expose: true
            access_type: public_method
            serialized_name: Code
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/austrianrules/2014/10'
            accessor:
                getter: getCode
                setter: setCode
            type: string
        message:
            expose: true
            access_type: public_method
            serialized_name: Message
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/austrianrules/2014/10'
            accessor:
                getter: getMessage
                setter: setMessage
            type: string
