Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V27\BankConfirmationDetails:
    xml_root_name: BankConfirmationDetails
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
