Psa\EpsBankTransfer\Internal\Generated\Protocol\V27\ConfirmationStatusRequest:
    xml_root_name: ConfirmationStatusRequest
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
