Psa\EpsBankTransfer\Internal\Generated\Protocol\V27\ConfirmationStatusResponse\ConfirmationStatusResponseAType:
    properties:
        sessionId:
            expose: true
            access_type: public_method
            serialized_name: SessionId
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
            accessor:
                getter: getSessionId
                setter: setSessionId
            type: string
        paymentConfirmationDetails:
            expose: true
            access_type: public_method
            serialized_name: PaymentConfirmationDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/payment/2025/01'
            accessor:
                getter: getPaymentConfirmationDetails
                setter: setPaymentConfirmationDetails
            type: Psa\EpsBankTransfer\Internal\Generated\Payment\V27\PaymentConfirmationDetails
        errorDetails:
            expose: true
            access_type: public_method
            serialized_name: ErrorDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
            accessor:
                getter: getErrorDetails
                setter: setErrorDetails
            type: Psa\EpsBankTransfer\Internal\Generated\Protocol\V27\ErrorDetails
