Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V27\ConfirmationStatusRequest\ConfirmationStatusRequestAType:
    properties:
        transactionId:
            expose: true
            access_type: public_method
            serialized_name: TransactionId
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
            accessor:
                getter: getTransactionId
                setter: setTransactionId
            type: string
        authenticationDetails:
            expose: true
            access_type: public_method
            serialized_name: AuthenticationDetails
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
            accessor:
                getter: getAuthenticationDetails
                setter: setAuthenticationDetails
            type: Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V27\AuthenticationDetails
