Externet\EpsBankTransfer\Generated\Protocol\V27\SHA256Fingerprint:
    xml_root_name: SHA256Fingerprint
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
