Psa\EpsBankTransfer\Internal\Generated\Protocol\V27\TransactionDetailsRequest:
    xml_root_name: TransactionDetailsRequest
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
