Psa\EpsBankTransfer\Internal\Generated\Protocol\V27\TransferInitiatorDetails:
    xml_root_name: TransferInitiatorDetails
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
