Psa\EpsBankTransfer\Internal\Generated\Protocol\V27\TransactionOkUrl\TransactionOkUrlAType:
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
        targetWindow:
            expose: true
            access_type: public_method
            serialized_name: TargetWindow
            accessor:
                getter: getTargetWindow
                setter: setTargetWindow
            xml_attribute: true
            type: \AnyType
