Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V27\VitalityCheckDetails\VitalityCheckDetailsAType:
    properties:
        remittanceIdentifier:
            expose: true
            access_type: public_method
            serialized_name: RemittanceIdentifier
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/epi/2013/02'
            accessor:
                getter: getRemittanceIdentifier
                setter: setRemittanceIdentifier
            type: string
        unstructuredRemittanceIdentifier:
            expose: true
            access_type: public_method
            serialized_name: UnstructuredRemittanceIdentifier
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/epi/2013/02'
            accessor:
                getter: getUnstructuredRemittanceIdentifier
                setter: setUnstructuredRemittanceIdentifier
            type: string
        orderingCustomerIdentifier:
            expose: true
            access_type: public_method
            serialized_name: OrderingCustomerIdentifier
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/epi/2013/02'
            accessor:
                getter: getOrderingCustomerIdentifier
                setter: setOrderingCustomerIdentifier
            type: string
