Knusperleicht\EpsBankTransfer\Internal\Generated\Protocol\V27\VitalityCheckDetails:
    xml_root_name: VitalityCheckDetails
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
