Externet\EpsBankTransfer\Generated\Protocol\V27\WebshopDetails\WebshopDetailsAType:
    properties:
        webshopArticle:
            expose: true
            access_type: public_method
            serialized_name: WebshopArticle
            xml_element:
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
            accessor:
                getter: getWebshopArticle
                setter: setWebshopArticle
            xml_list:
                inline: true
                entry_name: WebshopArticle
                namespace: 'http://www.stuzza.at/namespaces/eps/protocol/2025/01'
            type: array<Externet\EpsBankTransfer\Generated\Protocol\V27\WebshopArticle>
