Psa\EpsBankTransfer\Generated\Epi\Url:
    xml_root_name: Url
    xml_root_namespace: 'http://www.stuzza.at/namespaces/eps/epi/2013/02'
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
